### ISSUE TITLE
Heat balance for "lost", "transmitted" and "absorbed" rays

### ISSUE THREAD

**Issue by SergeyRa** [oasys-kit/ShadowOui-Advanced-Tools#3]
I performed some calculations for heat load consideration in front-end diamond windows (attached) and found that sum of "absorbed (lost)" + "absorbed (still good)" + "transmitted" power for second window (filter + aperture) differs by ~10% from the incident power.
In contrast, when physical aperture is not used (window 1 in the example), the sum of "absorbed (still good)" + "transmitted" power exactly equals incident power.
I can only suppose that probably heat load from absorbed by aperture rays (lost ones) is calculated _after_ applying filter attenuation to them.
[Heatload.zip](https://github.com/oasys-kit/ShadowOui-Advanced-Tools/files/5566035/Heatload.zip)

_P.S. Energy spread in the worksheet was set to to unrealistic 1e-6 intentionally_

**Comment by lucarebuffi** [comment]
The action of the filter is calculated by SHADOW (ray by ray, energy by energy), as clearly explained in the related paper: https://onlinelibrary.wiley.com/iucr/doi/10.1107/S160057752000778X
This is why it is called ab-initio procedure, because we don't take any decision, we don't apply any calculation, we just leave Shadow do the job and we don't "post-elaborate" its results.

I am completely confident that there are no mistakes in the Transmitted and Absorbed (still good) rays. 

I think the problem is in the Absorbed (Lost), because maybe Shadow apply the transmissivity to the rays even if they are lost, so I need to retrieve their intensity before the optical element to make the correct calculation. I will verify it asap.

Note: What is really important on the user side, is the sampling of the energy spectrum that can produce artifacts (as visible in your calculation)

To compute the power on a filter in front of the source, or on the first mirror, this tools is absolutely redundant and uselessly slow. We use it to compute more complicated cases and, mostly for pink and mono beam. 
In these simple cases, with white beam or pink from 1/2 mirrors (not focusing), you should use the SRCalc widget in XOPPY (refer to M. Sanchez del Rio for that), that is accurate and way faster.

**Comment by SergeyRa** [comment]
Thanks a lot!
The attached file actually is a part of larger calculation, where we use the 'ab initio' approach to properly consider heat transfer through focusing optics. The mentioned filters is just a part where we first noticed the discrepancy in the heat balance.

**Comment by lucarebuffi** [comment]
I understand. It is a minor bug in this specific calculation. You can keep going, while I analyze the issue.

**Comment by SergeyRa** [comment]
P.S. The same issue we also observe in case in apertured lens (attached [Lens1.zip](https://github.com/oasys-kit/ShadowOui-Advanced-Tools/files/5568677/Lens1.zip)).

**Comment by lucarebuffi** [comment]
Obviously. It depends on how shadow treats the absorption.

**Comment by lucarebuffi** [comment]
Dear Sergey, I verified and actually Shadow computes the absorption on the lost rays. To compensate this I retrieved the intensity of the lost rays from the incident beam and now the balance is correct. You can check this very easily, by analyzing the intensity of the lost rays after the first filter. You will see that is not 1 each anymore and that does not make sense, physically talking. 

Please update the ShadowOui Advanced Tools and verify by yourself.

Thank you for your feedback, it is very much appreciated.

**Comment by SergeyRa** [comment]
Many thanks!
